# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Welcome!
tagline:          ''
description:      'Welcome!' 
url:              "https://kcsadow.github.io"
baseurl:          "/website"
    
paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/kcsadow/website
  

