# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Project Name
tagline:          ''
description:      'Project Description' 
url:              "https://kcsadow.github.io"
baseurl:          "/website"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/kcsadow/website
