# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Personal Website
tagline:          ''
description:      'Personal Website' 
url:              "https://kcsadow.github.io"
baseurl:          "/website"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    
paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/kcsadow/website
  

